apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-quif
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-quif
    app.kubernetes.io/part-of: devfile-sample
  name: devfile-sample-quif
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-quif
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-quif
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sbudhwar-1-tenant/devfile-sample/devfile-sample-quif@sha256:7f928bc8af682358312c34511ddeb202e4a80fda1605d7d3e83feaa03b3b1591
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
