apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-quif
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-quif
    app.kubernetes.io/part-of: devfile-sample
  name: devfile-sample-quif
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-quif
status:
  loadBalancer: {}
